name: beykoz_nav
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localization:
  google_maps_flutter: ^2.10.1
  location: ^8.0.0
  geolocator: ^13.0.2
  http: ^1.3.0
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  flutter_tts: ^4.2.2
  awesome_notifications: ^0.10.1
  url_launcher: ^6.3.1
  path: ^1.9.1
  sqflite: ^2.4.2
  flutter_polyline_points: ^2.1.0
  flutter_settings_screens: ^0.3.4
  theme_provider: ^0.6.0
  flutter_slidable: ^4.0.0
  rxdart: ^0.28.0
  flutter_local_notifications: ^19.1.0
  permission_handler: ^12.0.0+1
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  google_fonts:
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  generate: true
  uses-material-design: true



  assets:
   - images/
   - icons/

dependency_overrides:
  intl: ^0.20.0